### ISSUE TITLE
Installing rubies that require gcc-4.2 fails due to PATH issues

### ISSUE THREAD

**Issue by a-warner** [boxen/puppet-ruby#116] opened 2014-09-24 03:17 UTC
One of the default rubies for boxen is `1.9.2-p320`, which, as specified in [Darwin.yaml](https://github.com/boxen/puppet-ruby/blob/master/data/Darwin.yaml), requires `gcc-4.2` to get built properly. I've configured boxen to install `gcc-4.2`, but it's not on the path at the time that boxen [attempts to build ruby](https://github.com/boxen/puppet-ruby/blob/bd8f0971f2cb98124b4e7770aaa440399b2b49c9/lib/puppet/provider/ruby/rubybuild.rb#L66).

The specific error is:

```
gcc-4.2: command not found
```

Even though boxen sets up the default Exec path [to include the homebrew bin dir](https://github.com/boxen/our-boxen/blob/fadfb2a9f4a3b58daaa79d1474dfcbf7900dc0df/manifests/site.pp#L14) (where the `gcc-4.2` executable ends up getting installed), `execute` doesn't seem to grab that default path, so it never sees the `gcc-4.2` executable?

Any suggestions here? Let me know if you need more information / if this makes any sense.

**Comment by mislav** [comment] 2015-01-29 01:16
`ruby-build` on OS X really likes when Homebrew's `bin` directory is in PATH because then it can then perform some optimizations (e.g. use gcc-4.2, re-use its newer OpenSSL library, etc.). Instead of symlinking gcc into `/usr/bin`, which is dangerous and hackish, we should simply ensure that Homebrew's bin directory is on PATH whenever we execute `ruby-build` or `rbenv install`.

**Comment by seanknox** [comment] 2015-04-26 17:30
@a-warner is this still an issue? I just installed 1.9.2-p320 without issue on a fresh Yosemite machine.

**Comment by a-warner** [comment] 2015-04-26 19:14
@seanknox I removed 1.9.2 from our manifest, so it might still be an issue but it's not currently affecting us

**Comment by seanknox** [comment] 2015-04-26 20:46
Gotcha. I'm unable to reproduce so I'm going to close this. Thanks for your detailed report and sorry there was such little movement on this until now.

**Closed by seanknox** 2015-04-26 20:46 UTC
